export declare enum Currency {
    BTC = "BTC",
    BCH = "BCH",
    LTC = "LTC",
    CELO = "CELO",
    ONE = "ONE",
    CUSD = "CUSD",
    CEUR = "CEUR",
    LUNA = "LUNA",
    LUNA_KRW = "LUNA_KRW",
    LUNA_USD = "LUNA_USD",
    ETH = "ETH",
    FABRIC = "FABRIC",
    QUORUM = "QUORUM",
    XRP = "XRP",
    XLM = "XLM",
    XBN = "XBN",
    USDC_XLM = "USDC_XLM",
    TUSDC_XLM = "TUSDC_XLM",
    DOGE = "DOGE",
    VET = "VET",
    NEO = "NEO",
    BNB = "BNB",
    BSC = "BSC",
    CAKE = "CAKE",
    BUSD_BSC = "BUSD_BSC",
    B2U_BSC = "B2U_BSC",
    BETH = "BETH",
    GAMEE = "GAMEE",
    BBTC = "BBTC",
    BADA = "BADA",
    RMD = "RMD",
    WBNB = "WBNB",
    BDOT = "BDOT",
    BXRP = "BXRP",
    BLTC = "BLTC",
    BBCH = "BBCH",
    MATIC = "MATIC",
    USDC_MATIC = "USDC_MATIC",
    USDC_BSC = "USDC_BSC",
    USDT = "USDT",
    GMC = "GMC",
    GMC_BSC = "GMC_BSC",
    FLOW = "FLOW",
    FUSD = "FUSD",
    USDT_TRON = "USDT_TRON",
    INRT_TRON = "INRT_TRON",
    TRON = "TRON",
    LEO = "LEO",
    LINK = "LINK",
    WBTC = "WBTC",
    UNI = "UNI",
    FREE = "FREE",
    MKR = "MKR",
    USDC = "USDC",
    MATIC_ETH = "MATIC_ETH",
    BAT = "BAT",
    TUSD = "TUSD",
    BUSD = "BUSD",
    PAX = "PAX",
    PLTC = "PLTC",
    XCON = "XCON",
    REVV = "REVV",
    SAND = "SAND",
    MMY = "MMY",
    PAXG = "PAXG",
    HAG = "HAG",
    LYRA = "LYRA",
    ADA = "ADA",
    XDC = "XDC",
    LATOKEN = "LATOKEN",
    USDT_MATIC = "USDT_MATIC",
    TUSDC_MATIC = "TUSDC_MATIC",
    SOL = "SOL",
    QTUM = "QTUM",
    EGLD = "EGLD",
    ALGO = "ALGO"
}

export { Currency as Assets };


export enum AvailableChains {
    BITCOIN = 'BITCOIN',
    ETHEREUM = 'ETHEREUM',
    POLYGON = 'POLYGON',
    DOGECOIN = 'DOGECOIN',
    LITECOIN = 'LITECOIN',
    BITCOINCASH = 'BITCOINCASH',
    TRON = 'TRON',
    FLOW = 'FLOW',
    CELO = 'CELO',
    XDC = 'XDC',
    RIPPLE = 'RIPPLE',
    STELLAR = 'STELLAR',
    SOLANA = 'SOLANA',
    VET = 'VET',
    NEO = 'NEO',
    BINANCE_CHAIN = 'BINANCE_CHAIN',
    BSC = 'BSC',
    LYRA = 'LYRA',
    ADA = 'ADA',
}

export const NativeAssets = {
    [AvailableChains.ETHEREUM]: "ETH",
    [AvailableChains.POLYGON]: "MATIC",
    [AvailableChains.TRON]: "TRON",
    [AvailableChains.CELO]: "CELO",
    [AvailableChains.BINANCE_CHAIN]: "BNB",
    [AvailableChains.BSC]: "BSC",
    [AvailableChains.BITCOIN]: "BTC",
    [AvailableChains.LITECOIN]: "LITECOIN",
    [AvailableChains.BITCOINCASH]: "BCH",
    [AvailableChains.XDC]: "XDC",
    [AvailableChains.STELLAR]: "XLM",
    [AvailableChains.SOLANA]: "SOL",
    [AvailableChains.RIPPLE]: "XRP",

}

export const Chains = {
    BTC: AvailableChains.BITCOIN,
    USDT: AvailableChains.ETHEREUM,
    DAI: AvailableChains.ETHEREUM,
    WBTC: AvailableChains.ETHEREUM,
    LEO: AvailableChains.ETHEREUM,
    LINK: AvailableChains.ETHEREUM,
    UNI: AvailableChains.ETHEREUM,
    FREE: AvailableChains.ETHEREUM,
    MKR: AvailableChains.ETHEREUM,
    USDC: AvailableChains.ETHEREUM,
    BAT: AvailableChains.ETHEREUM,
    TUSD: AvailableChains.ETHEREUM,
    BUSD: AvailableChains.ETHEREUM,
    PAX: AvailableChains.ETHEREUM,
    PAXG: AvailableChains.ETHEREUM,
    PLTC: AvailableChains.ETHEREUM,
    XCON: AvailableChains.ETHEREUM,
    ETH: AvailableChains.ETHEREUM,
    BSC: AvailableChains.BSC,
    BETH: AvailableChains.ETHEREUM,
    CAKE: AvailableChains.ETHEREUM,
    HAG: AvailableChains.ETHEREUM,
    BUSD_BSC: AvailableChains.BSC,
    USDC_BSC: AvailableChains.BSC,
    BBTC: AvailableChains.ETHEREUM,
    BADA: AvailableChains.ETHEREUM,
    WBNB: AvailableChains.ETHEREUM,
    BDOT: AvailableChains.ETHEREUM,
    BXRP: AvailableChains.ETHEREUM,
    BLTC: AvailableChains.ETHEREUM,
    BBCH: AvailableChains.ETHEREUM,
    MMY: AvailableChains.ETHEREUM,
    DOGE: AvailableChains.DOGECOIN,
    LTC: AvailableChains.LITECOIN,
    BCH: AvailableChains.BITCOINCASH,
    TRON: AvailableChains.TRON,
    USDT_TRON: AvailableChains.TRON,
    FLOW: AvailableChains.FLOW,
    FUSD: AvailableChains.FLOW,
    CELO: AvailableChains.CELO,
    CEUR: AvailableChains.CELO,
    CUSD: AvailableChains.CELO,
    XDC: AvailableChains.XDC,
    XRP: AvailableChains.RIPPLE,
    XLM: AvailableChains.STELLAR,
    USDC_XLM: AvailableChains.STELLAR,
    TUSDC_XLM: AvailableChains.STELLAR,
    VET: AvailableChains.VET,
    NEO: AvailableChains.NEO,
    BNB: AvailableChains.BINANCE_CHAIN,
    LYRA: AvailableChains.LYRA,
    ADA: AvailableChains.ADA,
    MATIC: AvailableChains.POLYGON,
    USDC_MATIC: AvailableChains.POLYGON,
    TUSDC_MATIC: AvailableChains.POLYGON,
    USDT_MATIC: AvailableChains.POLYGON,
    SOL: AvailableChains.SOLANA,
};
export const CUSTODIAL_GENESIS_ADDRESS_CONTRACT = {
    testnet: {
        [AvailableChains.ETHEREUM]: "0x472196fE753B3BB0f692Dfddc8acF508A88c1CD4",
        [AvailableChains.POLYGON]: "0x472196fE753B3BB0f692Dfddc8acF508A88c1CD4",
        [AvailableChains.BSC]: "0x472196fE753B3BB0f692Dfddc8acF508A88c1CD4"
    },
    mainnet: {
        [AvailableChains.ETHEREUM]: "0x472196fE753B3BB0f692Dfddc8acF508A88c1CD4",
        [AvailableChains.POLYGON]: "0x472196fE753B3BB0f692Dfddc8acF508A88c1CD4",
        [AvailableChains.BSC]: "0x472196fE753B3BB0f692Dfddc8acF508A88c1CD4"

    }
}

export const CUSTODIAL_ADDRESS_FACTORY_CONTRACT = {
    testnet: {
        [AvailableChains.ETHEREUM]: "0xd0e01E55EA387d4Fbb6a02b1C686B14BA558D690",
        [AvailableChains.POLYGON]: "0xd0e01E55EA387d4Fbb6a02b1C686B14BA558D690",
        [AvailableChains.BSC]: "0xd0e01E55EA387d4Fbb6a02b1C686B14BA558D690",
    },
    mainnet: {
        [AvailableChains.ETHEREUM]: "0xd0e01E55EA387d4Fbb6a02b1C686B14BA558D690",
        [AvailableChains.POLYGON]: "0xd0e01E55EA387d4Fbb6a02b1C686B14BA558D690",
        [AvailableChains.BSC]: "0xd0e01E55EA387d4Fbb6a02b1C686B14BA558D690",
    }
}